name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Make All
        run: make multi VERSION="${{ github.ref_name }}"

      - name: Publishing
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/Driver-C/tryssh@${{ github.ref_name }}
          GOPROXY=proxy.golang.org go list -m github.com/Driver-C/tryssh@latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
